/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.alexaleluia12


fun main() {
   str.doWork()
   println("######################")
   lst.doWork()
   println("######################")
   map.doWork()
   println("######################")
   file.read()
   file.write()
   println("######################")
}


