/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.alexaleluia12

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun appHasAGreeting() {
       
        assertNotNull("fake", "app should have a greeting")
    }
}
